=== miguel-amg/EngWeb2024/TPC1/bd/MRB-rua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="Tentidade" mixed="true">
        <xs:attribute name="tipo" type="TipoEntidade"/>
    </xs:complexType>
    <xs:simpleType name="TipoEntidade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pessoa"/>
            <xs:enumeration value="instituição"/>
            <xs:enumeration value="empresa"/>
            <xs:enumeration value="família"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:group name="misto">
        <xs:choice>
            <xs:element name="entidade" type="Tentidade"/>
            <xs:element name="lugar">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="norm" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="data" type="xs:string"/>
        </xs:choice>
    </xs:group>
    <xs:element name="rua">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="número" type="xs:string"/>
                            <xs:element name="nome" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corpo">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="para">
                                <xs:complexType mixed="true">
                                    <xs:group maxOccurs="unbounded" minOccurs="0" ref="misto"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lista-casas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="casa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="número" type="xs:string"/>
                                                  <xs:element minOccurs="0" name="enfiteuta"
                                                  type="xs:string" maxOccurs="unbounded"/>
                                                  <xs:element minOccurs="0" name="foro"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="desc">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="para">
                                                  <xs:complexType mixed="true">
                                                  <xs:group maxOccurs="unbounded" minOccurs="0"
                                                  ref="misto"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="vista"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="figura">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="imagem">
                                            <xs:complexType>
                                                <xs:attribute name="path" type="xs:string"
                                                  use="required"/>
                                                <xs:attribute name="largura" type="xs:int"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="legenda" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-30-CangostaDeSSebastiao.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Weeb_diogo/Desktop/publica%C3%A7%C3%A3o%20eletronica/aula8/MRB-rua.xsd">
    <meta>
        <número>30</número>
        <nome>Cangosta De S. Sebastião</nome>
    </meta>
    <corpo>
        <figura id="MRB-30-norte">
            <imagem path="../imagem/MRB-30-CangostaDeSSbebastiao-Norte.png"/>
            <legenda>Cangosta De S. Sebastião - norte</legenda>
        </figura>
        <figura id="MRB-30-sul">
            <imagem path="../imagem/MRB-30-CangostaDeSSbebastiao-Sul.png"/>
            <legenda>Cangosta De S. Sebastião - sul</legenda>
        </figura>
        <para>
            Longa rua extra-muros que descia toda a colina da <lugar>Cividade</lugar>, desde o <lugar>Terreiro de S. Sebastião</lugar> (onde estava a <lugar>capela de S.Sebastião das Carvalheiras)</lugar> até à do <lugar>Beco</lugar>.
        </para>
        <para>
            Decalcando talvez o cardo da cidade romana, e embora não conste no Tombo do <entidade entidade="instituição">Cabido</entidade> ( datável de <data>1369-1380</data>), esta rua já existia na Idade Média
            pois era uma das duas vias de ligação da cidade intra-muros com a <lugar>igreja paroquial de Maximinos</lugar>.
        </para>
        <para>
            Recebendo o nome de S. Sebastião por no seu topo estar a capela do santo da mesma invocação, de data de fundação desconhecida, esta rua só nos finais da
            década de setenta do nosso século perdeu o ar rual que ostentava em 1750.
        </para>
        <para>
            No Mappa, a rua era cosntítuida por casas de pedra, na sua grande maioria de um piso, muito simples, sendo 36% do tipo de porta/janela. Tinha
            vários portões que davam acesso directo a campos de cultivo, bem vísiveis atrás de muros que faceavam a rua , ou atrás das habitações.
        </para>
        <para>
            Das 25 casas do lado Norte e 24 do Sul, eram prazos do <entidade>Cabido</entidade> 20 casas do lado Norte.
        </para>
        <para>
            Mantém hoje o topónimo de S. Sebastião embora também seja conehcida por <lugar>rua dos Marchantes</lugar>.
        </para>
        
        <lista-casas>
            
            <casa>
                <número>1 e 2</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Pertencem ao n.º 38 da <lugar>Rua do Arrabalde da Cruz da Pedra</lugar>, para onde tem a frontaria e serventia pricnipais.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>3, 4, 5, 6, 7 e 8</número>
                <enfiteuta>Os herdeiros de Bento Vaz Perreira, da freguesia de S. Martinho de Dume, casado com Maria Josefa de Macedo e Castro.</enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Pagam foro ao n.º 20 da <lugar>Rua do Arrabalde da Cruz de Pedra</lugar>. Os n.º4 a 8 foram integrados na
                        escritura do prazo n.º 3.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>9</número>
                <!-- este enfiteuta tem de ser confirmado e todos os ** -->
                <enfiteuta>Os herdeiros de Bento Vaz Perreira, da freguesia de S. Martinho de Dume, casado com Maria Josefa de Macedo e Castro.</enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Pertence ao n.º 36 da Rua do Arrabalde da Cruz da Pedra, a qual, está integrada no prazo da casa n.º 20, da mesma rua.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>10</número>
                <enfiteuta>Os herdeiros de Bento Vaz Perreira, da freguesia de S. Martinho de Dume, casado com Maria Josefa de Macedo e Castro.</enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Pagam foro ao n.º 20 da <lugar>Rua do Arrabalde da Cruz de Pedra</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>11</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc>
                    <para> 
                        Portal de serventia da casa n.º 33 do Arrabalde da Cruz de Pedra.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>12, 13, 14 e 15</número>
                <enfiteuta>Os herdeiros de Bento Vaz Perreira, da freguesia de S. Martinho de Dume, casado com Maria Josefa de Macedo e Castro.</enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Casas que pagam foro ao n.º 20 da <lugar>Rua do Arrabalde da Cruz da Pedra</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>16 e 17</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Casa e portal de serventia do n.º 28 da <lugar>Rua do Arrabalde da Cruz da Pedra</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>19, 20 e 21</número>
                <enfiteuta>Os herdeiros de Bento Vaz Perreira, da freguesia de S. Martinho de Dume, casado com Maria Josefa de Macedo e Castro.</enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Corresponde a três casas que pagam foro ao n.º 20 da <lugar>Rua da Cruz da Pedra</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>22</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc>
                    <para>
                        Portal de serventia do campo da casa n.º 20 da <lugar>Rua do Arrabalde de Cruz da Pedra</lugar>. Confronta, do nascente, com casa 
                        pertencente à propriedade, denominada, «O Bispo».
                    </para>
                </desc>
            </casa>
            
        </lista-casas>
        
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-28-RuaDireita.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Weeb_diogo/Desktop/publica%C3%A7%C3%A3o%20eletronica/aula8/MRB-rua.xsd">
    <meta>
        <número>28</número>
        <nome>Rua Direita</nome>
    </meta>
    <corpo>
        <figura id="MRB-28-poente">
            <imagem path="../imagem/MRB-28-RuaDireita-Poente.png"/>
            <legenda>Rua Direita - poente</legenda>
        </figura>
        <figura id="MRB-28-nascente">
            <imagem path="../imagem/MRB-28-RuaDireita-Nascente.png"/>
            <legenda> Rua Direita - nascente</legenda>
        </figura>
        <para>
            Longa rua, no enfiamento da <lugar>rua Cruz de Pedra</lugar>, que se prolongava até ao
            <lugar>Monte das Penas</lugar>, ponto extremo da cidade onde havia uma igreja e que corresponde 
            actualmente ao espaço compreendido entre o <lugar>largo de Maximinos</lugar> e a <lugar>praça do Condestável</lugar>
        </para>
        <para>
            Aberta em data que desconhecemos torna-se notável pela ordenação dos seus edifícios,
            muito singelos, de pedra, com dois pisos, com porta e janela portadas de madeira no.º1 piso
            e com duas janelas bracarenses no andar superior; as empenas, corridas, estão quase todas ao mesmo nível.
            No extremo da rua, no <lugar>Monte das Penas</lugar>, vê-se uma casa grande, talvez de quinta e, a seu lado,
            ruínas de outra.
        </para>
        <para>
            Com 41 casas do lado Nascente e 29 do Poente, nenhuma destas casas, curiosamente, era prazo do Cabido.  
        </para>
        <para>
            Mantém actualmente o mesmo nome.
        </para>
        
        <lista-casas>
            <casa>
                <número>-</número>
                <enfiteuta>-</enfiteuta>
                <foro>-</foro>
                <desc>
                    <para>
                        Não tem casas foreiras ao cabido.
                    </para>
                </desc>
            </casa>
        </lista-casas>
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-47-RuaDeS.Barnabe.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/maria/OneDrive/%C3%81rea%20de%20Trabalho/UMINHO/4%C2%BA%20ANO/1%C2%BA%20SEMESTRE/Publica%C3%A7%C3%B5es%20Eletr%C3%B3nicas/PROJETO%20FINAL/MRB-rua.xsd">
    <meta>
        <número>47</número>
        <nome>Rua de S. Barnabé</nome>
    </meta>
    <corpo>
        <para>
            Pertencente ao complexo que tinha o centro na <lugar>praça do Gavião</lugar>, ligava as ruas de Santo André e da Oliveira.
            Artéria um pouco marginal a este conjunto, tem o seu prazo mais antigo em <data>1743</data>.
            Dividida em lotes, como todo o conjunto denominado de Quinteiro ou Gavião, ou, actualmente de <lugar>campo Novo</lugar>, tinha apenas ocupados com casas 18 dos 31 terrenos preparados para edificações. O restante espaço disponível, aqui assinalado com os n?s 8-20 e 23-24, eram as entradas ou muros de limite dos quintais da <lugar>rua dos Chãos de Cima</lugar>.
            As 20 casas desenhadas no Mappa são todas térreas, muito simples, do tipo de porta com janela lateral, mas com as «molduras» de pedra visíveis. Todas estas construções são prazos do<entidade tipo="instituição"> Cabido</entidade>.
            Mantém o nome de <lugar>S. Barnabé</lugar>.
        </para>
        <figura id="MRB-47-nascente">
            <imagem path="../imagem/MRB-47-RuaDeS.Barnabe-a(nascente).jpg"/>
            <legenda>Praça do Gavião - Nascente.</legenda>
        </figura>
        <figura id="MRB-47-poente">
            <imagem path="../imagem/MRB-47-RuaDeS.Barnabe-a(poente).jpg"/>
            <legenda>Praça do Gavião - Nascente.</legenda>
        </figura>
        <lista-casas>
            <casa>
                <número>1</número>
                <desc>
                    <para>
                        Pertence à casa n.° 14 da<lugar>Rua de Sto. André</lugar>, para onde tem a frontaria e serventia principais. 
                    </para>
                </desc>
            </casa>
            <casa>
                <número>2,3 e 4</número>
                <enfiteuta>D. Agostinha Maria de Barros, enfiteuta principal do prazo do casal dos Chãos ou Quinteiro.</enfiteuta>
                <desc>
                    <para>
                        <entidade tipo="pessoa">Isabel Maria de Jesus</entidade> paga 3240 reis ao enfiteuta do prazo do casal dos Chãos ou Quinteiro.
                        Encontram-se unidas desde <data>1743</data>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>5</número>
                <enfiteuta>D. Agostinha Maria de Barros, enfiteuta principal do prazo do casal dos Chãos ou Quinteiro.</enfiteuta>
                <desc>
                    <para>
                        <entidade tipo="pessoa">Antónia Francisca</entidade> paga 1325 reis ao enfiteuta do prazo do casal dos Chãos ou Quinteiro. Foi construída antes de <data>1745</data>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>6 e 7</número>
                <desc>
                    <para>
                        Pertence ao n.° 86 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>8</número>
                <desc>
                    <para>
                        Porta de serventia do quintal do n.° 85 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>9</número>
                <desc>
                    <para>
                        Porta de serventia do quintal do n.° 84 da Rua dos Chãos de Cima.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>10</número>
                <desc>
                    <para>
                        Porta de serventia do quintal do n.° 81 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>11</número>
                <desc>
                    <para>
                        Porta de serventia do quintal do n.° 80 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>12</número>
                <desc>
                    <para>
                        Porta de serventia dos quintais dos n.° 77 e 78 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>13</número>
                <desc>
                    <para>
                        Porta de serventia dos quintais dos n.° 75 e 76 da <lugar>rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>14</número>
                <desc>
                    <para>
                        Porta de serventia do quintal do n.° 74 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>15</número>
                <desc>
                    <para>
                        Quintal da casa n.° 72 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>16</número>
                <desc>
                    <para>
                        Quintal da casa n.° 71 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>17</número>
                <desc>
                    <para>
                        Quintal da casa n.° 70 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>18</número>
                <desc>
                    <para>
                        Quintal da casa n.° 69 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>19</número>
                <desc>
                    <para>
                        Quintal da casa n.° 68 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>20</número>
                <desc>
                    <para>
                        Quintal da casa n.° 67 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>21</número>
                <desc>
                    <para>
                        Pertence ao n.° 66 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>22</número>
                <desc>
                    <para>
                        Pertence ao n.° 64 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>23</número>
                <desc>
                    <para>
                        Porta do quintal da casa n.° 63 da <lugar>Rua dos Chãos de Cima</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>24</número>
                <desc>
                    <para>
                        Porta do quintal da casa n.° 62 da <lugar>Rua dos Chãos de Cima</lugar>.
                        Confronta, do nascente, com a viela que vai para a dita rua.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>25 a 37</número>
                <enfiteuta>D. Agostinha Maria de Barros, enfiteuta principal do prazo do casal dos Chãos ou Quinteiro.</enfiteuta>
                <desc>
                    <para>
                        «Chãos de casa» pertencentes ao prazo do casal dos Chãos ou Quinteiro.
                        O chão n.° 25 confronta, do norte, com o caminho que vai para <lugar>S. Vicente</lugar>.
                        
                    </para>
                </desc>
            </casa>
            <casa>
                <número>38 a 49</número>
                <enfiteuta>D. Agostinha Maria de Barros, enfiteuta principal do prazo do casal dos Chãos ou Quinteiro.</enfiteuta>
                <desc>
                    <para>
                        Pagam foro ao enfiteuta do prazo do casal dos Chãos ou Quinteiro.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>50</número>
                <enfiteuta>D. Agostinha Maria de Barros, enfiteuta principal do prazo do casal dos Chãos ou Quinteiro.</enfiteuta>
                <desc>
                    <para>
                        Pertence à casa n.° 15 da <lugar>Rua de Sto. André</lugar>, para onde tem a frontaria e serventia principais.
                    </para>
                </desc>
            </casa>
        </lista-casas>
    </corpo>
</rua>
