=== miguel-amg/EngWeb2024/TPC1/bd/MRB-rua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="Tentidade" mixed="true">
        <xs:attribute name="tipo" type="TipoEntidade"/>
    </xs:complexType>
    <xs:simpleType name="TipoEntidade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pessoa"/>
            <xs:enumeration value="instituição"/>
            <xs:enumeration value="empresa"/>
            <xs:enumeration value="família"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:group name="misto">
        <xs:choice>
            <xs:element name="entidade" type="Tentidade"/>
            <xs:element name="lugar">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="norm" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="data" type="xs:string"/>
        </xs:choice>
    </xs:group>
    <xs:element name="rua">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="número" type="xs:string"/>
                            <xs:element name="nome" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corpo">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="para">
                                <xs:complexType mixed="true">
                                    <xs:group maxOccurs="unbounded" minOccurs="0" ref="misto"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lista-casas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="casa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="número" type="xs:string"/>
                                                  <xs:element minOccurs="0" name="enfiteuta"
                                                  type="xs:string" maxOccurs="unbounded"/>
                                                  <xs:element minOccurs="0" name="foro"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="desc">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="para">
                                                  <xs:complexType mixed="true">
                                                  <xs:group maxOccurs="unbounded" minOccurs="0"
                                                  ref="misto"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="vista"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="figura">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="imagem">
                                            <xs:complexType>
                                                <xs:attribute name="path" type="xs:string"
                                                  use="required"/>
                                                <xs:attribute name="largura" type="xs:int"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="legenda" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-21-RuaVerde.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../MRB-rua.xsd">
    <meta>
        <número>21</número>
        <nome>Rua Verde</nome>
    </meta>
    <corpo>
        <para>Longa rua, com início no <lugar>postigo de S. Sebastião</lugar> e fim na
            <lugar>rua de Maximinos</lugar>. O seu traçado prolongava-se, porém, até à
            <lugar>Porta de S. Francisco</lugar>, através das
            <lugar>ruas dos Sapateiros e do Campo</lugar>.</para>
        <para>Decalcando, uma rua da cidade romana, era esta a mais ocidental das artérias
            intra-muros da velha urbe medieval.</para>
        <para>Ponto privilegiado nas ligações com <lugar norm="rua de Maximinos">Maximinos</lugar> e a
            <lugar>capela de S. Sebastião</lugar>, o seu traçado foi no séc. XIX (inícios?)
            violentamente rompido com a continuação da rua das travessas, que, abrindo uma brecha
            nas muralhas, a ligou com o <lugar>campo de S. Miguel o Anjo</lugar>; no fim do mesmo
            século, por volta de <data>1880</data>, foi alargada, sendo destruídas todas as casas,
            excepto uma, de dois pisos, no seu extremo Norte, recebendo então o nome de D. Frei
            Caetano Brandão.</para>
        <para>Em <data>1750</data> apresentava-se dividida em duas: uma, a Norte da
            <lugar>rua das Travessas</lugar> com o nome de rua Verde; outra, a Sul, chamada somente
            <lugar>Couto do Arvoredo</lugar>.</para>
        <para>O <lugar>Couto do Arvoredo</lugar> estava parcialmente construído (ainda hoje, aliás,
            do lado Este conserva os quintais; e os do Oeste só nos anos 60 e 70 do nosso séc. foram
            ocupados com habitações), com casas simples, de 2 pisos, de um tipo mais frequente fora
            de muralhas, nos arrabaldes, sem varandas e com as janelas apenas tapadas por portas de
            madeira.</para>
        <para>A <lugar>rua Verde</lugar>, embora apresente um tipo de casa também muito simples, e
            de contrução sem dúvida arcaica, estava já em <data>1750</data> toda construída. Mantém,
            todas as casas apenas com dois pisos (excepto duas), com aberturas predominantemente
            tapadas por portadas de madeira, raríssimas gelosias e varandas e algumas casas com
            janela do tipo bracarense. Muito curiosos são os primeiros cinco edifícios do lado
            Nascente e uma boa parte dos do Poente: são geralmente de dois vãos, 2 pisos, porta no
            rés do chão e 2 janelas no andar, com um ritmo bem marcado e, sobretudo, com o sobrado
            muito pronunciado, mostrando bem a fragilidade dos seus materiais construtivos.</para>
        <para>Das 24 casas do lado Nascente e 33 do Poente, 3 e 13 são, respectivamente, prazos do
            Cabido.</para>
        
        <figura id="MRB-21-nascente">
            <imagem path="../imagem/MRB-21-RuaVerde-nascente.jpg"/>
            <legenda>Rua Verde - nascente.</legenda>
        </figura>
        <figura id="MRB-21-poente">
            <imagem path="../imagem/MRB-21-RuaVerde-poente.jpg"/>
            <legenda>Rua Verde - poente.</legenda>
        </figura>
        
        <lista-casas>
            <casa>
                <número>1</número>
                <enfiteuta>Maria Catarina do Céu, religiosa do Salvador</enfiteuta>
                <foro>170 reis e 2 galinhas</foro>
                <desc>
                    <para>Confronta, do sul, com casa foreira à cororaria.</para>
                </desc>
            </casa>
            <casa>
                <número>2</número>
                <enfiteuta>Faustina Pereira</enfiteuta>
                <foro>180 reis e 1 galinha</foro>
                <desc>
                    <para>A enfiteuta é filha de <entidade tipo="pessoa">Francisco
                            Rodrigues</entidade>, torneiro.</para>
                    <para>Confronta, do norte, com casa foreira à cororaria. Entre os anos de
                        <data>1670</data> e <data>1724</data> esteve unida ao n.º 3.</para>
                </desc>
            </casa>
            <casa>
                <número>3</número>
                <enfiteuta>Constantino Teixeira</enfiteuta>
                <foro>175 reis e 1 galinha</foro>
            </casa>
            <casa>
                <número>4</número>
                <desc>
                    <para>Corresponde, desde o ano <data>1627</data>, à casa n.º 12 da
                        <lugar>Rua de St.º António</lugar>. Encontra-se situada defronte do
                        <lugar>postigo de S. Sebastião</lugar>.</para>
                </desc>
            </casa>
            <casa>
                <número>5, 6 e 7</número>
                <enfiteuta>António Pereira, sapateiro</enfiteuta>
                <foro>100 reis e 1 galinha</foro>
                <desc>
                    <para>O enfiteuta é filho de <entidade tipo="pessoa">Teresa da Costa</entidade>
                        e de seu marido <entidade tipo="pessoa">António Pereira</entidade>.</para>
                    <para>Encontram-se situadas junto ao <lugar>postigo de S. Sebastião</lugar> e
                        foram construídas, antes de <data>1563</data>, no
                        <lugar>«lugar do Sabugal»</lugar>, pertencente ao n.º 12 da
                        <lugar>Rua de Sto. António.</lugar></para>
                </desc>
            </casa>
            <casa>
                <número>8</número>
                <enfiteuta>Teresa da Costa, viúva de António Pereira</enfiteuta>
                <foro>2 galinhas</foro>
                <desc>
                    <para>Quintal denominado do Sabugal, que foi de <entidade tipo="pessoa">José de
                            Araújo Teixeira</entidade>.</para>
                </desc>
            </casa>
            <casa>
                <número>9 e 10</número>
                <enfiteuta>Salvador Pinto, guarda da Sé</enfiteuta>
                <foro>220 reis e 2 galinhas</foro>
                <desc>
                    <para>Estão unidas, num só prazo, desde o ano de <data>1549</data>. A casa n.º
                        9, confronta, do sul com casa foreira ao <entidade tipo="instituição"
                            >Hospital de S. Marcos</entidade>.</para>
                </desc>
            </casa>
            <casa>
                <número>11</número>
                <desc>
                    <para>Paga pensão à obra da Sé. São enfiteutas os herdeiros de <entidade
                            tipo="pessoa">Maria Ribeiro</entidade>, que pagam 80 reis de
                        foro.</para>
                </desc>
            </casa>
            <casa>
                <número>12</número>
                <enfiteuta>José Pereira, sapateiro</enfiteuta>
                <foro>95 reis e 1 galinha</foro>
                <desc>
                    <para>O enfiteuta foi dotado com esta casa.</para>
                </desc>
            </casa>
            <casa>
                <número>13</número>
                <enfiteuta>Manuel da Costa Vasconcelos</enfiteuta>
                <foro>320 reis e 7 galinhas</foro>
            </casa>
            <casa>
                <número>14</número>
                <enfiteuta>Padre Matias de Lemos</enfiteuta>
                <foro>30 reis e 2 galinhas</foro>
                <desc>
                    <para>Entre os anos de <data>1609</data> e <data>1640</data> pertenceu ao n.º
                        13.</para>
                </desc>
            </casa>
            <casa>
                <número>15 e 16</número>
                <enfiteuta>Manuel da Costa Vasconcelos</enfiteuta>
                <foro>265 reis e 2 galinhas</foro>
            </casa>
            <casa>
                <número>17 e 18</número>
                <enfiteuta>Os herdeiros de Duarte Mendes de Oliveira</enfiteuta>
                <foro>1 galinha</foro>
                <desc>
                    <para>Os enfiteuras pagavam um foro muito pequeno, dado que as casas tinham sido
                        consideradas arruinadas no último emprazamento, etectuado no ano de
                        <data>1673</data>.</para>
                    <para>Confrontam, do Sul, com casas foreiras ao <entidade tipo="instituição"
                            >Hospital de S. Marcos</entidade>.</para>
                </desc>
            </casa>
            <casa>
                <número>19</número>
                <enfiteuta>Manuel Vieira</enfiteuta>
                <foro>225 reis e 2 galinhas</foro>
                <desc>
                    <para>Estas casas tinham pertencido a <entidade tipo="pessoa">Isabel da
                            Silva</entidade> e, anteriormente, a <entidade tipo="pessoa">Julião
                            Lopes</entidade>.</para>
                </desc>
            </casa>
            <casa>
                <número>20</número>
                <desc>
                    <para>Corresponde ao n.º 12 da <lugar norm="rua de Maximinos">Rua de Maximinos</lugar>, para onde tem a
                        fronteira e serventia principais.</para>
                </desc>
            </casa>
        </lista-casas>
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-26-SaoMiguelOAnjo.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Users/pedro/Desktop/MRB-rua.xsd">
    <meta>
        <número>26</número>
        <nome>Rua de S.Miguel O Anjo</nome>
    </meta>
    <corpo>
        <figura id="MRB-26-norte">
            <imagem path="../imagem/MRB-26-SaoMiguelOAnjo-Norte.png"/>
            <legenda>Rua de S.Miguel O Anjo - Norte</legenda>
        </figura>
        <figura id="MRB-26-sul">
            <imagem path="../imagem/MRB-26-SaoMiguelOAnjo-Sul.png"/>
            <legenda>Rua de S.Miguel O Anjo - Sul</legenda>
        </figura>
        <para> 
            Pequena artéria extra-muros que ligava a <lugar>rua Em Frente dos Açogues</lugar>,com
            o <lugar>campo das Hortas</lugar> e a <lugar>rua de Cruz de Pedra</lugar>.          
        </para>
        <para>
            Decalcando um troço do possível traçado da muralha da cidade romana e na pendente da 
           <lugar>capela de S.Miguel o Anjo</lugar>, era já conhecida na Idade Média com o nome de 
            <lugar>rua de Maximinos</lugar>. Destruída totalmente em <data>1384</data>, por 
            <entidade tipo="pessoa">D. João de Castela</entidade>, perdem-se depois as notícias sobre 
            a sua história.
        </para>
        <para>
            Em <data>1750</data> era uma rua talvez sem comércio, com muitas casas de sobrado, algumas
            varandas, muitas janelas com gelosias e apenas 4 edifícios totalmente construídos em pedra.
            Destas, três situavam-se curiosamente em gavetos: as casas do prazo nº8 e a 9 e a que lhe 
            ficava contígua. Esta tinha ainda a característica de apresentar uma das raras pedras de 
            armas de heráldica de família, a dos <entidade tipo="pessoa">Bravos</entidade>, existente 
            então na cidade.
        </para>
        <para>
            Das 14 casas do lado Norte e 11 do Sul, era prazos do <entidade tipo="instituição">Cabido</entidade> oito e uma, respectivamente.
        </para>
        <para>
            Desde 1891 que se chama <lugar>rua Visconde Pindela</lugar>
        </para>
        <lista-casas>
            <casa>
                <número>1</número>
                <enfiteuta>Inácio Peixoto</enfiteuta>
                <foro>50 reis e 1 galinha</foro>
                <desc>
                    <para>
                        Pertenceu ao <entidade tipo="pessoa">Padre João Rodrigues</entidade>.
                        Confronta, do norte com <lugar>casa foreira à Mitra</lugar>.
                        Foi construída depois de <data>1539</data> em pertenças do nº2.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>2 e 3</número>
                <enfiteuta>Padre Pedro Francisco</enfiteuta>
                <foro>100 reis e 2 galinhas</foro>
                <desc>
                    <para>
                        A casa nº2 confronta, do poente, com o <lugar>rossio</lugar> que está
                        no princípio da <lugar>Rua da Cruz da Pedra.</lugar>
                    </para>
                </desc>
            </casa>
            <casa>
                <número>4</número>
                <enfiteuta>Gregório José Braga, alfaiate</enfiteuta>
                <foro>25 reis e 1 galinha</foro>
                <desc>
                    <para>
                        Foi construída, depois de <data>1555</data>, em pertenças do número 2.
                        Confronta, do nascente, com casa foreira à <lugar>Câmara</lugar>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>5</número>
                <foro>5 reis(de censo)</foro>
                <desc>
                    <para>
                        Os livros das pensões referem que esta casa foi de <entidade tipo="pessoa">João Gomes</entidade>,
                        genro do <entidade tipo="pessoa">Mestre Gonçalo</entidade>, «e que há muitos anos se não paga 
                        este censo».
                    </para>
                </desc>
            </casa>
            <casa>
                <número>6</número>
                <foro>5 reis(de censo)</foro>
                <desc>
                    <para>
                        O censo é pago por <entidade tipo="pessoa">Mónica Veloso de Freitas</entidade>, viúva.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>7</número>
                <foro>5 reis(de censo)</foro>
                <desc>
                    <para>
                        Pertenceu <entidade tipo="pessoa">Pedro Martins</entidade>.
                        O censo é pago <entidade tipo="pessoa">Gaspar de Medeiros</entidade>.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>8</número>
                <desc>
                    <para>
                        Pertence ao nº1 da rua em frente do <lugar>Açogue</lugar> para onde tem 
                        frontaria e serventia principais.
                    </para>
                </desc>
            </casa>
            <casa>
                <número>9</número>
                <enfiteuta>D.António de Noronha de Mesquita Soares</enfiteuta>
                <desc>
                    <para>
                        A casa e parte do quintal são foreiras ao <entidade tipo="instituição">Hospital de S.Marcos</entidade>.
                        Pela outra parte do quintal paga-se, de foro, 451 reis ao nº1 do Campo de S.Sebastião. Encontra-se
                        subemprazada aos herdeiros do <entidade tipo="pessoa">Padre António Velho Maciel</entidade>, beneficiado.
                        
                    </para>
                </desc>
            </casa>       
        </lista-casas>
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-03-RuaDosAcouguesVelhos.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/In%C3%AAs/Desktop/4%C2%BA%20Ano%20(2018-2019)/1%C2%BA%20Semestre/Publica%C3%A7%C3%A3o%20Eletr%C3%B3nica/MRB-rua.xsd">
    <meta>
        <número>3</número>
        <nome>Rua dos Açougues velhos</nome>
    </meta>
    <corpo>
        <figura id="MRB-03-nascente">
            <imagem path="../imagem/MRB-03-RuaDosAcouguesVelhos-nascente.PNG"/>
            <legenda>Rua dos Açougues Velhos - vista nascente. </legenda>
        </figura>
        <figura id="MRB-03-poente">
            <imagem path="../imagem/MRB-03-RuaDosAcouguesVelhos-poente.PNG"/>
            <legenda>Rua dos Açougues Velhos - vista poente. </legenda>
        </figura>
        <para>Pequenina rua que liga a fachada da <lugar>Sé</lugar> com a <lugar>rua Nova</lugar>.</para>
         <para>Aberta possivelmente na Idade Media nela existiram ate ao <data>sec. XV</data> os açougues da cidade. Nessa data a rua era mais longa, prolongando-se até quase ao início da <lugar>rua do Poço</lugar>.</para>
         <para>Actualmente poucas alterações de peso há nesta rua quanto ao Mappa e nenhuma respeitante ao seu tamanho e largura. O edifício pertencente à <lugar>Sé</lugar> foi porém substancialmente aumentado em altura, apresentando-se hoje radicalmente diferente.</para>
          <para>Pena foi que as casas dos prazos n.° 3 e 4 desta rua, ja em <data>1750</data> com um só inquilino, tivessem sido destruídos, pois apresentavam uma curiosíssima janela de canto e um jogo de telhados estranho.</para>
        <para>Das duas casas do lado Norte e 6 do Sul pertenciam ao <entidade tipo="instituição">Cabido</entidade> 1 e 6 respectivamente.</para>
        <para>Não sabemos quando o seu nome mudou para a <lugar>rua do Cabido</lugar>. No mapa de <data>1857</data> tem ainda o nome de <lugar>Travessa dos Açougues Velhos</lugar>.</para> 
        <lista-casas>
            <casa>
                <número>1</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc><para>Corresponde à casa nº16 da <lugar>Praça do Pão</lugar> para onde tem a frontaria e serventia principais. </para></desc>
            </casa>
            <casa>
                <número>2,3,4</número>
                <enfiteuta>Padre Francisco Xavier de Campos</enfiteuta>
                <foro>610 reis e 1 capão</foro>
                <desc><para>Estas casas foram construídas depois de <data>1550</data>, em pertenças do nº16, da <lugar>Praça do Pão</lugar> e, desde o ano de <data>1725</data>, constituem um só prazo.</para></desc>
            </casa>
            <casa>
                <número>5</número>
                <enfiteuta>Teresa Tomásia, viúva de Agostinho Marques da Silva, ourives</enfiteuta>
                <foro>105 reis e 1 galinha</foro>
                <desc><para>A última porta do nº6, para o lado do norte, é serventia do nº7 da <lugar>rua Nova</lugar>. Encontram-se unidas desde o ano de <data>1641</data>.</para></desc>
            </casa>
            <casa>
                <número>6</número>
                <enfiteuta>Teresa Tomásia, viúva de Agostinho Marques da Silva, ourives</enfiteuta>
                <foro>120 reis e 1 galinha</foro>
                <desc><para>A última porta do nº6, para o lado do norte, é serventia do nº7 da <lugar>rua Nova</lugar>. Encontram-se unidas desde o ano de <data>1641</data>.</para></desc>
            </casa>
            <casa>
                <número>7 e 8</número>
                <desc><para>Desde do ano <data>1644</data> que correspondem ao nº5 da <lugar>Rua Nova de Sousa</lugar>, para onde têm a frontaria e serventia principais.</para></desc>
            </casa>
            <casa>
                <número>9</número>
                <enfiteuta>Pedro Pereira</enfiteuta>
                <foro>40 reis e 1 galinha</foro>
                <desc><para>Foi demolida para alargamento das casas do <entidade tipo="instituição">Cabido</entidade>, depois do ano de <data>1793</data>.</para></desc>
            </casa>
        </lista-casas>
        
    </corpo>
</rua>
