=== miguel-amg/EngWeb2024/TPC1/bd/MRB-rua.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="Tentidade" mixed="true">
        <xs:attribute name="tipo" type="TipoEntidade"/>
    </xs:complexType>
    <xs:simpleType name="TipoEntidade">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pessoa"/>
            <xs:enumeration value="instituição"/>
            <xs:enumeration value="empresa"/>
            <xs:enumeration value="família"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:group name="misto">
        <xs:choice>
            <xs:element name="entidade" type="Tentidade"/>
            <xs:element name="lugar">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="norm" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="data" type="xs:string"/>
        </xs:choice>
    </xs:group>
    <xs:element name="rua">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="número" type="xs:string"/>
                            <xs:element name="nome" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corpo">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="para">
                                <xs:complexType mixed="true">
                                    <xs:group maxOccurs="unbounded" minOccurs="0" ref="misto"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lista-casas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="casa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="número" type="xs:string"/>
                                                  <xs:element minOccurs="0" name="enfiteuta"
                                                  type="xs:string" maxOccurs="unbounded"/>
                                                  <xs:element minOccurs="0" name="foro"
                                                  type="xs:string"/>
                                                  <xs:element minOccurs="0" name="desc">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="para">
                                                  <xs:complexType mixed="true">
                                                  <xs:group maxOccurs="unbounded" minOccurs="0"
                                                  ref="misto"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element minOccurs="0" name="vista"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="figura">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="imagem">
                                            <xs:complexType>
                                                <xs:attribute name="path" type="xs:string"
                                                  use="required"/>
                                                <xs:attribute name="largura" type="xs:int"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="legenda" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-60-CangostaDaRuaDasAguas.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="MRB-rua.xsd">
    <meta>
        <número>60</número>
        <nome>Cangosta da Rua das Águas</nome>
    </meta>
    <corpo>
        <para> Pequena artéria que partindo da <lugar>rua das Águas</lugar> passava pela quingosta da <lugar>Palha</lugar> e de dirigia ao <lugar>Campo de Nossa Senhora a Branca</lugar>. No volume 2, dos Índices das Casas dos Prazos do <lugar>Cabido</lugar>, a páginas 273-278 é chamada Cangosta Que Vai Para Nossa Senhora a Branca.</para>
        <para>No Mappa não há, porém, indicações de que estes edifícios sejam foreiros ao <lugar>Cabido</lugar>, o que cintraria os Índices.</para> 
        <para> A 7 casas que vemos no Mappa são bastante simples, pobres até, de arquitetura tradicional. Seis são térreas e uma tem três pisos, sendo o último andar, contudo, mais baixo e de mais pequenas aberturas.</para>
        <para>Em <data> 1891 </data>a Câmara decidiu fazer um pequeno largo <lugar>(o Rechicho)</lugar> no seu extremo Oeste e alargá-la.</para>
        <para> Atual <lugar>rua do Raio e largo João Penha (ou do Rechicho). </lugar></para>        
        <figura id="MRB-60-norte">
            <imagem path="../imagem/MRB-60-CangostaDaRuaDasAguas-norte.jpg"/>
            <legenda>Cangosta da Rua das Águas - norte.</legenda>
        </figura>
        <lista-casas>
            <casa>
                <número>37 a 42</número>
                <enfiteuta>*Vid.casa nº33 da Rua das Águas (rua 36)</enfiteuta>
                <desc> 
                   <para> A numeração que lhe é atribuída pelos índices dá seguimento à da <lugar>rua das Águas</lugar>.</para>
                    <para>A casa nº37 confronta, de poente, com o nº36 da <lugar>rua das Águas</lugar>.</para>
                </desc>
            </casa>
        </lista-casas>
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-35-RuaDeSMarcosRuaDosGranjinhos.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/tiago/OneDrive/Documents/workspace_xml/trabalhofinal/MRB-rua.xsd">
    <meta>
        <número>35</número>
        <nome>Rua de S. Marcos</nome>
    </meta>
    <corpo>
        <para>
            Envolvia muralha, do lado Este, e ligava o exterior da <lugar>Porta do Souto</lugar>ao <lugar>campo dos Remédios</lugar>.
        </para>
        <para>
            Aberta no tempo de <entidade tipo="pessoa">D. Diogo de Sousa</entidade> rapidamente se encheu de casas no alçado Nascente; o <entidade tipo="instituição">Cabido</entidade>, que aqui tem aforada apenas uma casa e o <entidade tipo="instituição">convento dos Remédios</entidade>, era já senhor de um prazo em <data>1515</data>. O lado Poente, que encostava à muralha, não tinha nenhuma edificação em <data>1594</data>, segundo o mapa de Braunio.
        </para>
        <para>
            Esta rua, onde existe o último exemplar completo de casa com gelosias, tão vulgar nas artérias principais de <lugar>Braga</lugar> em <data>1750</data>, não está representada no Mappa porque pertencia à <entidade tipo="instituição">Câmara</entidade>. E é pena porque, para além da imagem que nos transmitiria, nos poderia dar muitos elementos que agora só documentalmente poderemos obter. Uma última informação fica: no último quartel do séc. XIX agrupavam-se aqui as principais oficinas de escultores santeiros da cidade. Seria também assim no séc. XVIII?
        </para>
        <para>
            Mantém ainda hoje o mesmo nome.
        </para>     
        
        <lista-casas>
            <casa>
                <número>1</número>
                <enfiteuta>António de Araújo Ferreira, alfaiate</enfiteuta>
                <foro>70 reis</foro>
                <desc>
                    <para>
                        Confronta, do norte, com casa foreira à <lugar>capela de Sta. Luzia</lugar>, ou <lugar>morgado de Besteiros</lugar>, e, do sul, com o nº 2 (<lugar>Convento dos Remédios</lugar>). Foi construída, juntamente com os nº 2, 3 e 4, depois do ano de <data>1515</data>, no local onde existia uma vinha.
                    </para>                      
                </desc>
            </casa>
            <casa>
                <número>2, 3 e 4</número>
                <desc>
                    <para>
                        Através de um contrato de escambo, realizado no ano de <data>1544</data>, o cabido cedeu a <entidade tipo="pessoa">D. André de Torquemada, Bispo de Dume</entidade>, parte dos terrenos das casas existentes neste local, a fim de se erirgir o <lugar>convento de Nossa Senhora dos Remédios</lugar>. A portaria deste convento foi, assim, construída em parte daqueles quintais.
                    </para>
                    <para>
                        Posteriormente, no ano de <data>1734</data>, o cabido escambou as casas, que foram demolidas, sendo o terreno integrado no referido convento. Todas as casas estavam incorporadas no nº 1, da qual se separaram através de escrituras de prazo realizadas em <data>1630</data>, <data>1642</data> e <data>1714</data>, referentes às casas nº 4, 3 e 2, respectivamente.
                    </para>
                </desc>
            </casa>         
        </lista-casas>
        
        <figura id="MRB3-5-a">
            <imagem path="../imagem/MRB-35-RuaDeSMarcosRuaDosGranjinhos-primeira.jpg"/>
            <legenda>Rua de São Marcos - Nascente</legenda>
        </figura>
        
        <nome>Rua dos Granjinhos</nome>
        <para>
            Mandada abrir por <entidade tipo="pessoa">D. Diogo de Sousa</entidade> em terreno acidentado, estabelecia uma ligação rápida entre a <lugar>porta de S. João</lugar> e a <lugar>rua da Ponte de Guimarães</lugar>. Aquele arcebispo instalou também aqui uma fonte em <data>1509</data>.
        </para>
        <para>
            Aberta em plena zona rural, de certo modo nas traseiras do <lugar>hospital de S. Marcos</lugar>, esta artéria mostra muitas casas do tipo de porta ladeada de janela, no piso térreo. Uma única habitação aparece aqui bem cuidada, com «molduras» em pedra nas portas e janelas: todas as outras, são simples e de pedra – excepto a do prazo nº 1 - mais ou menos bem tratadas, avultando 3 com varandas.
        </para>
        <para>
            De salientar ainda que quase todas as janelas são do tipo bracarense.
        </para>
        <para>
            Tendo no Mappa apenas desenhado o seu lado Nascente, tinha então 32 casas, 9 das quais eram prazos do <entidade tipo="instituição">Cabido</entidade>.
        </para>
        <para>
            A <lugar norm="Rua dos Granjinhos">rua dos Granjinhos</lugar> corresponde hoje à metade Sul das ruas de <lugar norm="Rua de S. Lázaro">S. Lázaro</lugar> e dos <lugar norm="Rua dos Granjinhos">Granjinhos</lugar>.
        </para>
        
       <lista-casas>
           <casa>
               <número>1</número>
               <enfiteuta>Manuel Fernandes da Silva, mestre de pedraria</enfiteuta>
               <foro>480 reis e 4 galinhas</foro>
               <desc>
                   <para>
                       Faziam parte do prazo as vertentes das águas do <lugar>Hospital de S. Marcos</lugar>.
                   </para>
                   <para>
                       Os de nº 1 a 6 foram construídos em <data>1508</data>, no local onde existia uma vinha. No  meio dos quintais das casas nº 1 e 2 encontra-se um caminho de serventia de «terra encapelada», ou seja, com encargo de missas em <lugar norm="Campo e Calçada de Nossa Senhoora a Branca ">Nossa Senhora a Branca</lugar> e em <lugar>S. João do Souto</lugar>.
                   </para>
                   <para>
                       O nº 1 confronta, do norte, com a <lugar>cangosta da Palmatória</lugar>.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>2 e 3</número>
               <enfiteuta>Manuel Fernandes da Silva, mestre de pedraria</enfiteuta>
               <foro>40 reis</foro>
           </casa>
           <casa>
               <número>4, 5 e 6</número>
               <enfiteuta>Manuel Fernandes da Silva, mestre de pedraria</enfiteuta>
               <foro>150 reis e 1 galinha</foro>
               <desc>
                   <para>
                       O nº 6 confronta, do sul, com casa de herdade dízima a Deus.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>7</número>
               <enfiteuta>Os herdeiros de João Marques, da Rua de S. Marcos, casado com Catarina de Araújo</enfiteuta>
               <foro>160 reis e 2 galinhas</foro>
               <desc>
                   <para>
                       Leiras situadas nas <lugar>hortas dos Granginhos</lugar>, abaixo da <lugar>Fonte do Ídolo</lugar>, e nas <lugar>Hortas de S. Marcos</lugar>, atrás da <lugar>Fonte de S. Marcos</lugar>.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>8</número>
               <desc>
                   <para>
                        Quintal da casa nº 25 da <lugar>Rua de S. Lázaro</lugar>.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>9 e 10</número>
               <enfiteuta>Pedro Gomes de Basto, c.c. Maria de Magalhães</enfiteuta>
               <desc>
                   <para>
                        O <entidade tipo="pessoa">Padre António Ferreira Torres</entidade> paga de foro, 202 reis ao nº 42 da <lugar>Rua de S. Lázaro</lugar>.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>11</número>
               <enfiteuta>Pedro Gomes de Basto, c.c. Maria de Magalhães</enfiteuta>
               <desc>
                   <para>
                       <entidade tipo="pessoa">Mariana Dias, viúva</entidade> paga 305 reis ao nº 42 da <lugar>Rua de S. Lázaro</lugar>.
                   </para>
               </desc>
           </casa>
           <casa>
               <número>12</número>
               <enfiteuta>Pedro Gomes de Basto, c.c. Maria de Magalhães</enfiteuta>
               <desc>
                   <para>
                       O <entidade tipo="pessoa">Padre José Ferreira, vigário de Covas</entidade>, paga 100 reis, ao nº 42 da <lugar>Rua de S. Lázaro</lugar>.
                   </para>
                   <para>
                       Confronta, do sul, com o <lugar>terreiro de S. Lázaro</lugar> e, do poente, com a <lugar>Rua dos Granginhos</lugar>.
                   </para>
               </desc>
           </casa>         
       </lista-casas>
        
        <figura id="MRB-35-b">
            <imagem path="../imagem/MRB-35-RuaDeSMarcosRuaDosGranjinhos-segunda.jpg"/>
            <legenda>Rua dos Granjinhos - Nascente</legenda>
        </figura>
        
    </corpo>
</rua>

=== miguel-amg/EngWeb2024/TPC1/bd/texto/MRB-05-RuaDasOucias.xml
<?xml version="1.0" encoding="UTF-8"?>
<rua xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/In%C3%AAs/Desktop/4%C2%BA%20Ano%20(2018-2019)/1%C2%BA%20Semestre/Publica%C3%A7%C3%A3o%20Eletr%C3%B3nica/MRB-rua.xsd">
    <meta>
        <número>5</número>
        <nome>Rua das Oucias</nome>
    </meta>
    <corpo>
        <figura id="MRB-05">
            <imagem path="../imagem/MRB-05-RuaDasOucias.png"/>
            <legenda>Rua das Oucias.</legenda>
        </figura>
        
        <para>
            Tortuosa rua que contornava as traseiras e fachada lateral Sul da <lugar>Sé</lugar>.</para>
        <para>
            Longa e atribulada história tem esta via, que, no espaço curto, quase de notícia, como convém a esta edição, não pode ser aqui contada. </para>
        <para>   
            Formada, naturalmente, pelo isolamento que os monumentos religiosos sempre têm, as suas casas foram lentamente surgindo. </para> 
        <para>
            No ponto de encontro desta rua com a <lugar>rua do Souto </lugar>desembocava o «cano» que, vindo de lugar desconhecido, abastecia a principal fonte da cidade medieval,
            a <lugar>fonte de S. Geraldo</lugar>, que por aqui se deveria localizar. Junto, no local onde está a <lugar>Capela da Glória</lugar>, existiu a <lugar>casa do Conselho Municipal</lugar> demolida para 
            dar lugar àquela capela.</para>
        <para>Com <entidade tipo="pessoa">D. Diogo de Sousa</entidade>, em 1509, a <lugar>capela mor da Sé</lugar> foi profundamente alterada, e, embora não tenha avançado sobre os alicerces da velha 
            construção medieval, deu-lhe outra leveza, que o manuelino, nos seus rendilhados, sempre tem. Poucos anos após o mesmo arcebispo mandou abrir a <lugar>rua de S. João </lugar>,
            permitindo uma ligação directa com a <lugar>Porta de S. João</lugar>.</para>
        <para>No pequeno «rexio» existente do <lugar>lado Sul da Sé, entre o braço do transepto e a fachada</lugar>, existiu, na Idade Média,
            uma feira de olarias. </para>
        <para>Toda esta parte foi violentamente destruída nos anos quarenta do nosso século, para «limpar esta zona socialmente tão degradada» criando-se o <lugar>Rocio 
            da Sé</lugar>. E na sequência dessa obra de «limpeza» constroem-se, em «estilo Português Suave», o <lugar>edifício do Tribunal do Trabalho/Delegação Escolar</lugar> e um outro, particular; e, 
            passados vinte anos, foi destruído um grande e nobre edifício setecentista, para se construir a <lugar>Residência Académica</lugar>.</para> 
        <para>Hoje a rua conserva todos os seus belíssimos edifícios na zona 
            correspondente à <lugar>rua de Nossa Senhora do Leite</lugar>. Na parte Sul toda a malha urbanística e escala arquitectónica desapareceu com a introdução do novo e amplo <lugar>Rocio da Sé</lugar>, que, no Mappa
            apenas conserva uma casa. </para>
        <para>Das 15 casas existentes, 12 eram prazos do Cabido.</para>
        <para>A designação de Oucias (e aparecem também as designações de Ussias e Adussias), 
            será talvez uma corrupção de ousia, isto é capela-mor. E a de <entidade tipo="pessoa">Nossa Senhora do Leite</entidade> é devida à belíssima imagem, da <lugar>escola coimbrã</lugar> do séc. XVI, que foi oferecida por <entidade tipo="pessoa">D. Diogo de Sousa </entidade>.
        </para>
        <lista-casas>
            <casa>
                <número>1</número>
                <enfiteuta></enfiteuta>
                <foro>38 reis e 6 pretos (de censo)</foro>
                <desc>
                    <para>A casa é foreira aos Padres coreiros. O censo é pago por <entidade tipo="pessoa">Domingos José de Melo.</entidade></para></desc>
            </casa>
            <casa>
                <número>2</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc><para>Corresponde ao nº1 da <lugar>Rua de S.João</lugar>, para onde tem a frontaria e serventia principais.</para></desc>
            </casa>
            <casa>
                <número>3 e 4</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc><para>Corresponde ao nº 11 da <lugar>Rua de S. João</lugar>, para onde tem a frontaria e serventia principais. 
            </para>
                </desc>
            </casa>
            
           
            <casa>
                <número>5</número>
                <enfiteuta>Custódio Rodrigues, boticário </enfiteuta>
                <foro> 440 reis e 2 galinhas</foro>
                <desc><para>Confronta, do nascente, com <lugar>casa de herdade dízima a Deus</lugar>. Foi unida, em <data>1621</data>, à casa nº 6.</para></desc>
            </casa>
            
            <casa>
                <número>6</número>
                <enfiteuta>Custódio Rodrigues, boticário</enfiteuta>
                <foro>345 reis e 2 galinhas</foro>
                <desc><para>Confronta, do nascente, com casa de herdade dízima a Deus. Foi unida, em <data>1621</data>, à casa nº 6.</para></desc>
            </casa>
            <casa>
                <número>7</número>
                <enfiteuta></enfiteuta>
                <foro>160 reis (de censo)</foro>
                <desc><para>Confronta, do poente, com o <lugar>Terreiro das Oussias</lugar>. <entidade tipo="pessoa">António Xavier Rebelo</entidade>, tercenário, paga de censo 160 reis.    </para></desc>
            </casa>
            
            <casa>
                <número>8</número>
                <enfiteuta> Dr. Manuel José Brandão</enfiteuta>
                <foro>700 reis e 2 galinhas</foro>
                <desc><para>O enfiteuta possuia esta casa por sucessão de <entidade tipo="pessoa">Frutuoso Brandão Pereira</entidade> e de <entidade tipo="pessoa">Maria Josefa da Costa,</entidade> sua mulher. Confronta, do sul, com o nº 2 da <lugar>Rua Pequena.</lugar></para></desc>
            </casa>
            <casa>
                <número>9</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc><para>Confronta, do norte, com o <lugar>Terreiro das Oussias</lugar>; do sul, com o nº 8, da <lugar>Rua Pequena</lugar>; do nascente, com a mesma <lugar>Rua Pequena</lugar> e, 
                    do poente, com quintal de uma casa da <lugar>Rua de Sta. Maria ou do Poço</lugar>. </para>
                    <para>Foi demolida, depois do ano de <data>1750</data>, "para a obra da <lugar>sacristia da Sé</lugar>,
                    por conta da fábrica da mesma Sé".</para></desc>
            </casa>
            <casa>
                <número>10 e 11</número>
                <enfiteuta></enfiteuta>
                <foro></foro>
                <desc><para> Não aparecem desenhadas no Mapa por terem sido demolidas "para a obra da <lugar>sacristia da Sé"</lugar>. A casa nº 10 situava-se no canto desta rua (parte nascente) e confrontava do norte, defronte da Sé, com a <lugar>Rua das Oussias</lugar> e, do nascente com o caminho que se dirigia das Oussias para a <lugar>Rua Pequena</lugar>. A casa nº 11 confronta, do nascente, com a nº 10. </para></desc>
            </casa>
            <casa>
                <número>12</número>
                <enfiteuta>Custódia Pereira, mulher de João Fernandes Gentil</enfiteuta>
                <foro>550 reis, 2 galinhas e 2 capões</foro>
                <desc><para> Foi comprada pela <entidade tipo="empresa">Fábrica da Sé</entidade> que a mandou demolir depois de <data>1750</data>, para a "obra da sacristia".</para><para>Confronta, do nascente, com o <lugar>Terreiro das Oussias</lugar> e, do norte com o mesmo Terreiro e com o nº 13.</para></desc>
            </casa>
            
            <casa>
                <número>13</número>
                <enfiteuta>Francisca Teresa</enfiteuta>
                <foro>400 reis e 2 galinhas</foro>
                <desc><para>A enfiteuta sucedeu a seu irmão, o Reitor de Freitas,<entidade tipo="pessoa">José Ferreira Petiz</entidade>,  sendo ambos filhos de <entidade tipo="pessoa">Francisco Gonçalves Petiz</entidade>, pasteleiro.</para><para> Confronta, do nascente, com o nº 14; do norte e poente com a rua e, do sul com a nº 12.</para></desc>
            </casa>
            <casa>
                <número>14</número>
                <enfiteuta>Francisca Teresa</enfiteuta>
                <foro>400 reis e 2 galinhas</foro>
                <desc><para> Confronta, do nascente, com o nº 13 e, do poente com o nº 15.</para><para> Foi construída em <data>1547</data>, em pertenças da casa nº 13.</para></desc>
            </casa>
            
            <casa>
                <número>15</número>
                <enfiteuta> António Antunes, pasteleiro, e sua mulher, Joana Francisca</enfiteuta>
                <foro> 330 reis e 2 galinhas</foro>
            </casa>
            
            <casa>
                <número>16 e 17</número>
                <enfiteuta>David Lopes</enfiteuta>
                <foro>820 reis e 2 galinhas</foro>
                <desc><para>A casa nº16 foi unida ao nº17, no ano de <data>1667 </data>. O nº17 confronta com a <lugar>Rua do Poço </lugar>.
                </para></desc>
            </casa>
            
            
            
            
            
            
            
        </lista-casas>
    </corpo>
</rua>
